routes/web.php
<?php

use App\Http\Controllers\GuestHostsController;
use App\Http\Controllers\GuestVolunteersController;
use App\Http\Controllers\HostsController;
use App\Http\Controllers\KlimasofasController;
use App\Http\Controllers\VolunteersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('homepage');

Route::get('/dashboard', function () {
    return view('dashboard');
})
    ->middleware(['auth'])
    ->name('dashboard');

require __DIR__ . '/auth.php';

/*
|--------------------------------------------------------------------------
| Static pages
|--------------------------------------------------------------------------
*/

Route::view('datenschutz', 'static.datenschutz')->name('static.datenschutz');
Route::view('impressum', 'static.impressum')->name('static.impressum');
Route::view('klimasofa/danke', 'static.danke-klimasofa')->name(
    'static.danke-klimasofa',
);
Route::view('mitmachen/danke', 'static.danke-mitmachen')->name(
    'static.danke-mitmachen',
);

/*
|--------------------------------------------------------------------------
| Guest routes
|--------------------------------------------------------------------------
*/

Route::get('klimasofa', [GuestHostsController::class, 'create'])->name(
    'guesthosts.create',
);
Route::post('klimasofa', [GuestHostsController::class, 'store'])->name(
    'guesthosts.store',
);

Route::get('mitmachen', [GuestVolunteersController::class, 'create'])->name(
    'guestvolunteers.create',
);
Route::post('mitmachen', [GuestVolunteersController::class, 'store'])->name(
    'guestvolunteers.store',
);

/*
|--------------------------------------------------------------------------
| Authenticated user routes
|--------------------------------------------------------------------------
*/

Route::prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function () {
        Route::resource('hosts', HostsController::class);

        Route::resource('volunteers', VolunteersController::class);

        Route::resource('klimasofas', KlimasofasController::class);
    });

app/Http/Controllers/GuestHostsController.php
<?php

namespace App\Http\Controllers;

use App\Mail\HostRegistrationNotify;
use App\Mail\HostRegistrationSuccess;
use App\Models\Host;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class GuestHostsController extends Controller
{
    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('guesthosts.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): RedirectResponse
    {
        $attributes = $request->validate([
            'name' => 'required',
            'address' => 'required',
            'email' => 'required|email',
            'phone' => 'required',
            'guests' => 'required|integer',
            'rooms' => 'required|integer',
            'has_beamer' => 'required|boolean',
            'has_white_wall' => 'required|boolean',
            'found' => 'nullable',
            'date1' => 'required|date|after:+6 days',
            'date2' => 'required|date|after:+6 days',
            'privacy' => 'accepted',
        ]);

        $host = Host::create($attributes);

        $mailable = new HostRegistrationSuccess($host);
        Mail::to($host)->send($mailable);

        // @todo: include the url to the host for the team
        $mailable = new HostRegistrationNotify($host);
        Mail::to(env('MAIL_FROM_ADDRESS'))->send($mailable);

        return redirect()->route('static.danke-klimasofa');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/guesthosts/create.blade.php
<x-guest-layout>
    <x-slot name="header">
        Ein Klimasofa veranstalten
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white shadow-sm sm:rounded-lg">
                <div class="sm:p-6 bg-white">
                    <p class="mb-8">
                        Wenn du ein Klimasofa veranstalten möchtest, brauchen wir
                        von dir ein paar Daten, damit wir mit der Planung beginnen
                        können.
                    </p>

                    <x-validation-errors class="mb-8" :errors="$errors"/>

                    <form action="{{ route('guesthosts.store') }}" method="POST">
                        @csrf
                        <x-label for="name">Name:</x-label>
                        <x-input type="text" name="name" id="name" placeholder="Name" required autofocus
                                 class="mb-6 w-full" :value="old('name')"></x-input>

                        <x-label for="address">Adresse:</x-label>
                        <x-input type="text" name="address" id="address" placeholder="Adresse" required
                                 class="mb-6 w-full" :value="old('address')"></x-input>

                        <div class="sm:flex">
                            <div class="mb-6 sm:w-1/2 sm:mr-6">
                                <x-label for="email">E-Mail:</x-label>
                                <x-input type="email" name="email" id="email" placeholder="E-Mail" required
                                         class="w-full"
                                         :value="old('email')"></x-input>
                            </div>

                            <div class="mb-6 sm:w-1/2">
                                <x-label for="phone">Telefon:</x-label>
                                <x-input type="tel" name="phone" id="phone" placeholder="Telefon" required
                                         class="w-full"
                                         :value="old('phone')"></x-input>
                            </div>
                        </div>

                        <div class="sm:flex">
                            <div class="mb-6 sm:w-1/2 sm:mr-6">
                                <x-label for="guests">Anzahl der Teilnehmer*innen:</x-label>
                                <x-input type="number" name="guests" id="guests" placeholder="Anzahl" required
                                         class="w-full"
                                         :value="old('guests')"></x-input>
                            </div>

                            <div class="mb-6 sm:w-1/2">
                                <x-label for="rooms">Anzahl der Räume:</x-label>
                                <x-input type="number" name="rooms" id="rooms" placeholder="Räume" required
                                         class="w-full"
                                         :value="old('rooms')"></x-input>
                            </div>
                        </div>

                        <div class="sm:flex">
                            <div class="mb-6 sm:w-1/2 sm:mr-6">
                                <x-label for="date1">Wunschdatum 1:</x-label>
                                <x-input type="date" name="date1" id="date1" required class="w-full"
                                         :value="old('date1')"></x-input>
                            </div>

                            <div class="mb-6 sm:w-1/2">
                                <x-label for="date2">Wunschdatum 2:</x-label>
                                <x-input type="date" name="date2" id="date2" required class="w-full"
                                         :value="old('date2')"></x-input>
                            </div>
                        </div>

                        <div class="sm:flex">
                            <div class="flex items-center mb-6 sm:w-1/2 sm:mr-6">
                                <x-label for="has_beamer" class="mr-2">Ist ein Beamer vorhanden?</x-label>
                                <select name="has_beamer" id="has_beamer"
                                        class="rounded-md shadow-sm border-gray-300 focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                                    <option></option>
                                    <option value="1" @if (old('has_beamer') === '1') {{ 'selected' }} @endif>Ja
                                    </option>
                                    <option value="0" @if (old('has_beamer') === '0') {{ 'selected' }} @endif>Nein
                                    </option>
                                </select>
                            </div>

                            <div class="flex items-center mb-6 sm:w-1/2">
                                <x-label for="has_white_wall" class="mr-2">Ist eine weiße oder helle Wand für den Beamer
                                    vorhanden?
                                </x-label>
                                <select name="has_white_wall" id="has_white_wall"
                                        class="rounded-md shadow-sm border-gray-300 focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                                    <option></option>
                                    <option value="1" @if (old('has_white_wall') === '1') {{ 'selected' }} @endif>Ja
                                    </option>
                                    <option value="0" @if (old('has_white_wall') === '0') {{ 'selected' }} @endif>Nein
                                    </option>
                                </select>
                            </div>
                        </div>

                        <x-label for="found">Wie oder wodurch bist du auf uns aufmerksam geworden?</x-label>
                        <x-input type="text" name="found" id="found"
                                 class="mb-6 w-full" :value="old('found')"></x-input>

                        <div class="flex items-center mb-6">
                            <x-input type="checkbox" name="privacy" id="privacy" class="mr-3"></x-input>
                            <x-label for="privacy">Ich habe die <a href="{{ route('static.datenschutz') }}" class="text-klimasofa-red hover:underline">Datenschutzerklärung</a>
                                gelesen und willige in die Speicherung und Verarbeitung meiner Daten ein.
                            </x-label>
                        </div>

                        <div class="flex justify-center">
                            <input type="submit" value="Abschicken"
                                   class="inline-flex px-6 py-3 transition ease-in-out duration-300 hover:bg-klimasofa-green-dark focus:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50 bg-klimasofa-green text-white text-center text-sm font-semibold uppercase tracking-wide rounded-lg shadow-lg mr-3">

                            <a href="{{ route('homepage') }}" role="button"
                               class="inline-flex px-6 py-3 transition ease-in-out duration-300 hover:bg-gray-400 focus:border-blue-500 focus:outline-none focus:ring focus:ring-blue-500 focus:ring-opacity-50 bg-gray-300 text-black text-center text-sm font-semibold uppercase tracking-wide rounded-lg shadow-lg">
                                Abbrechen
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-guest-layout>