routes/web.php
<?php

use App\Http\Controllers\GuestHostsController;
use App\Http\Controllers\GuestVolunteersController;
use App\Http\Controllers\HostsController;
use App\Http\Controllers\KlimasofasController;
use App\Http\Controllers\VolunteersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('homepage');

Route::get('/dashboard', function () {
    return view('dashboard');
})
    ->middleware(['auth'])
    ->name('dashboard');

require __DIR__ . '/auth.php';

/*
|--------------------------------------------------------------------------
| Static pages
|--------------------------------------------------------------------------
*/

Route::view('datenschutz', 'static.datenschutz')->name('static.datenschutz');
Route::view('impressum', 'static.impressum')->name('static.impressum');
Route::view('klimasofa/danke', 'static.danke-klimasofa')->name(
    'static.danke-klimasofa',
);
Route::view('mitmachen/danke', 'static.danke-mitmachen')->name(
    'static.danke-mitmachen',
);

/*
|--------------------------------------------------------------------------
| Guest routes
|--------------------------------------------------------------------------
*/

Route::get('klimasofa', [GuestHostsController::class, 'create'])->name(
    'guesthosts.create',
);
Route::post('klimasofa', [GuestHostsController::class, 'store'])->name(
    'guesthosts.store',
);

Route::get('mitmachen', [GuestVolunteersController::class, 'create'])->name(
    'guestvolunteers.create',
);
Route::post('mitmachen', [GuestVolunteersController::class, 'store'])->name(
    'guestvolunteers.store',
);

/*
|--------------------------------------------------------------------------
| Authenticated user routes
|--------------------------------------------------------------------------
*/

Route::prefix('admin')
    ->name('admin.')
    ->middleware('auth')
    ->group(function () {
        Route::resource('hosts', HostsController::class);

        Route::resource('volunteers', VolunteersController::class);

        Route::resource('klimasofas', KlimasofasController::class);
    });

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'Laravel') }}</title>
        <link rel="stylesheet" href="{{ asset(mix('css/app.css')) }}">
        <script src="{{ asset(mix('js/app.js')) }}" defer></script>
    </head>
    <body>
        <div class="min-h-screen bg-gray-200">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    <h2>
                        {{ $header }}
                    </h2>
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="stylesheet" href="{{ asset(mix('css/app.css')) }}">
    <script src="{{ asset(mix('js/app.js')) }}" defer></script>
</head>
<body class="bg-gray-200 antialiased text-gray-900">
<div class="min-h-screen max-w-screen-2xl mx-auto bg-white shadow-md lg:p-2 lg:px-6">
    <div>
        <nav class="p-1 text-klimasofa-green lg:flex lg:justify-between items-center mb-2">
            <a href="{{ url(route('homepage')) }}"
               class="flex items-center justify-center space-x-2 md:space-x-4 border-b-2 border-gray-200 pb-4 mb-4 lg:border-none lg:pb-0 lg:mb-0">
                <img src="{{ asset(mix('svg/klimasofa-logo.svg')) }}"
                     class="w-16 md:w-auto" alt="Klimasofa-Logo"/>
                <span class="font-extrabold text-2xl md:text-3xl">Klimasofa-Planung</span>
            </a>
            <div class="flex flex-row justify-center space-x-4">
                <a href="{{ url(route('guesthosts.create')) }}"
                   class="transition ease-in-out duration-300 hover:bg-klimasofa-green-dark bg-klimasofa-green text-white text-center text-sm font-semibold uppercase tracking-wide py-3 rounded-lg w-36 shadow-lg">
                    Anfragen
                </a>
                <a href="{{ url(route('guestvolunteers.create')) }}"
                   class="transition ease-in-out duration-300 hover:bg-klimasofa-green-dark bg-klimasofa-green text-white text-center text-sm font-semibold uppercase tracking-wide py-3 rounded-lg w-36 shadow-lg">
                    Mitmachen
                </a>
            </div>
        </nav>
        <div class="relative h-56 lg:h-96">
            <img class="absolute inset-0 h-full w-full object-cover object-center"
                 src="{{ asset(mix('images/forest.jpg')) }}" alt="Foto eines Regenwalds">
            <svg class="absolute bottom-0 fill-current text-white" viewBox="0 0 1482 144">
                <path d="M 0,102 C 144,49 300,38 452,58 c 122,12 238,52 358,71 230,36 469,-17 672,-129 V 144 H 0 Z"/>
            </svg>
            <h1 class="relative text-white text-center pt-20 lg:pt-36 lg:text-4xl">
                {{ $header ?? '' }}
            </h1>
        </div>
    </div>
    <div class="p-4 lg:p-1 mt-2">
        {{ $slot }}
    </div>
    <div class="p-4 lg:p-1 mt-8">
        <div class="border-t-2 border-gray-200">
            <h2 class="mt-4 text-klimasofa-green text-center">
                Gefördert aus Mitteln des #moinzukunft – Hamburger Klimafonds
            </h2>
            <div class="flex flex-col mt-4 md:flex-row justify-center items-center">
                <a href="https://moinzukunft.hamburg/klimafonds/">
                    <img src="{{ asset(mix('images/logo-hamburger-klimafonds.png')) }}" class="mb-4" alt="Logo des Hamburger Klimafonds">
                </a>
                <p class="text-sm mb-4 md:w-1/4 md:mx-6">
                    Ein Projekt der Hamburger Klimaschutzstiftung und der
                    Behörde für Umwelt, Klima, Energie und Agrarwirtschaft (BUKEA)
                </p>
                <a href="https://gut-karlshoehe.de/hamburgerklimaschutzstiftung/">
                    <img src="{{ asset(mix('images/logo-hamburger-klimaschutzstiftung.png')) }}" class="mb-4" alt="Logo der Hamburger Klimaschutzstiftung">
                </a>
            </div>
        </div>
    </div>
    <footer class="my-4 text-center text-klimasofa-green">
        <p>
            <a href="{{ url(route('static.impressum')) }}" class="mr-6">Impressum</a>
            <a href="{{ url(route('static.datenschutz')) }}">Datenschutz</a>
        </p>
    </footer>
</div>
</body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600"/>
                    </a>
                </div>

            @auth
                <!-- Navigation Links -->
                    <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                        <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                            {{ __('Dashboard') }}
                        </x-nav-link>
                    </div>

                    <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                        <x-nav-link :href="route('admin.hosts.index')" :active="request()->routeIs('admin.hosts.index')">
                            Gastgebende
                        </x-nav-link>
                    </div>
                @endauth
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button
                            class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 20 20">
                                    <path fill-rule="evenodd"
                                          d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                          clip-rule="evenodd"/>
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                             onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Logout') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open"
                        class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex"
                              stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M4 6h16M4 12h16M4 18h16"/>
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round"
                              stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
            <x-responsive-nav-link :href="route('admin.hosts.index')" :active="request()->routeIs('admin.hosts.index')">
                Gastgebende
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
                    </svg>
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                                           onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Logout') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>